### PR TITLE
Use html download btn

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
@CagtayFabry after #31 pytest does not run at all, any idea?

**Comment by CagtayFabry** [comment]
> @CagtayFabry after #31 pytest does not run at all, any idea?

no that's weird, it ran on the PR and main branch push...

**Comment by marscher** [comment]
Yes, I saw that too. It is strange. It has to be something which only applies on main branch after the merge.

**Comment by marscher** [comment]
well on main, pytest got just executed. And this PR does not change the workflows or pytest cfg... wtf

**Comment by marscher** [comment]
I didn't know that PR creators have to enable something, if they want their code tested on the main repository. That's super weird m$ logic, isn't it?

**Comment by marscher** [comment]
Just checked the Actions settings of my fork, everything was enabled (by default).

**Comment by marscher** [comment]
on my fork pytest is executed: https://github.com/marscher/weldx-widgets/runs/4078401150?check_suite_focus=true

**Comment by CagtayFabry** [comment]
whatever is causing this, it wasn't working even before #31: https://github.com/BAMWelDX/weldx-widgets/pull/28/checks

**Comment by CagtayFabry** [comment]
can you try rebasing this?

**Comment by marscher** [comment]
Merge or Rebase shouldn't make any difference. I just tried a merge, without any luck.

**Comment by marscher** [comment]
rebase same thing. Eventually I should delete my fork and redo this.

**Pull request closed without merging**
